# Generated by Django 2.2.5 on 2019-10-02 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BasicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FileName_text', models.CharField(max_length=200)),
                ('modify_date', models.DateTimeField(verbose_name='date published')),
                ('FilePath_text', models.CharField(max_length=200)),
                ('FileID', models.IntegerField(default=0)),
                ('tag_text', models.CharField(default='', max_length=200)),
                ('status', models.CharField(default='new', max_length=10)),
            ],
        ),
    ]
