# Generated by Django 2.2.5 on 2019-10-03 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myfile', '0002_auto_20191003_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicinfo',
            name='status',
            field=models.IntegerField(choices=[(0, ''), (1, 'opencv'), (2, 'python'), (3, 'c++'), (4, 'ROS'), (5, 'Linux'), (6, '计算机视觉'), (7, '机器学习'), (8, 'Django'), (9, '数学算法')], default=0, help_text='选择类型', verbose_name='归类'),
        ),
    ]
